- name: Deploy nginx configuratuin file
  template:
    src: mysite.j2
    dest: /etc/nginx/sites-enabled/mysite
  notify: restart nginx

- name: Remove default config
  file: path=/etc/nginx/sites-enabled/default state=absent