- hosts: webservers
  become: yes
  vars:
    http_port: 8000
    https_port: 4443
    html_welcome_msg: "Hello from Ansible"
  roles:
    - common
    - apache2


- hosts: proxy
  become: yes
  roles:
    - common
    - nginx