---
- name: Debug hostvars
  hosts: loadbalancer
  gather_facts: yes
  tasks:
    - name: Show ansible_facts for myproxy
      debug:
        var: hostvars['myproxy']['ansible_facts']['nodename']

    - name: Save Ansible facts to a file
      copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: "/tmp/debug_facts.json"

    - name: Fetch the file to local machine
      fetch:
        src: "/tmp/debug_facts.json"
        dest: "logs/debug_facts_nodename.json"
        flat: yes