---
- hosts: webservers
  become: yes
  gather_facts: yes
  roles:
    - common
    - apache2
  tags:
    - web

#inject gather facts to force the playbook to gather facts
- hosts: all
  gather_facts: true
  become: true
  # tasks : 
  #   - name: gather facts
  #     command: date
  tags:
    - always

- hosts: myproxy
  become: yes
  gather_facts: yes
  roles:
    - common
    - nginx
  tags:
    - proxy

- hosts: database
  become: yes
  roles:
    - common
    - mysql
  tags:
    - database