---
- hosts: webservers
  become: yes
  gather_facts: yes
  roles:
    - common
    - apache2
  tags:
    - web


- hosts: myproxy
  become: yes
  gather_facts: yes
  roles:
    - common
    - nginx
  tags:
    - proxy

- hosts: database
  become: yes
  roles:
    - common
    - mysql
  tags:
    - database