---
- name: Create my.cnf configuration file
  template:
    src: templates/my.cnf.j2
    dest: /etc/mysql/conf.d/mysql.cnf
  notify: restart mysql

- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"


- name: Create mysql database with name 'first_db'
  mysql_db:
    name: "{{ mysql_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: mysqldb

- name: Create mysql user with name 'john' and password 'password' with all privileges
  mysql_user:
    name: john
    password: john
    priv: '*.*:ALL'
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: mysqldb