---
- name: install common packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - pydf
    - tree
    - open-vm-tools
    - htop
    - vim
  tags: 
    - installation